#!/bin/bash

set -e

# Start mysql
sudo /etc/init.d/mysql start
sudo mysql -e 'CREATE DATABASE IF NOT EXISTS `json-table-test`'

# Run stack init when stack.yaml is missing.
if [ ! -f stack.yaml ]
then
  stack init
fi

# Build and run test
stack build && stack run mysql-json-table-test
